### ISSUE TITLE
FTP issues

### ISSUE THREAD

**Issue by Lingomat** [langtech/aikuma#128]
If Aikuma fails an operation it keeps retrying. This should not happen. Only connection failures should result in a new attempt and it should be a re-try of the entire sync event. The current behavior caused my FTP server to block the IP address as malicious. This had to do with not providing permissions to delete files. 

With all appropriate permissions on an XLite Windows FTP server, a sync attempt results in a crash. The resulting FTP log shows the activity to this point. This also happens on Windows smallftpd but no log is provided by that software.

1/29/2013 11:37:21 (not login 192.168.1.1<--192.168.1.2:21) "220 Xlight FTP Server 3.7 ready..."
11/29/2013 11:37:22 (not login 192.168.1.1-->192.168.1.2:21) "USER aikuma"
11/29/2013 11:37:22 (not login 192.168.1.1<--192.168.1.2:21) "331 Password required for aikuma"
11/29/2013 11:37:22 (not login 192.168.1.1-->192.168.1.2:21) "PASS *****"
11/29/2013 11:37:22 (aikuma 192.168.1.1<--192.168.1.2:21) "230 Login OK"
11/29/2013 11:37:22 (aikuma 192.168.1.1-->192.168.1.2:21) "TYPE I"
11/29/2013 11:37:22 (aikuma 192.168.1.1<--192.168.1.2:21) "200 Type set to I."
11/29/2013 11:37:22 (aikuma 192.168.1.1-->192.168.1.2:21) "CWD /"
11/29/2013 11:37:22 (aikuma 192.168.1.1<--192.168.1.2:21) "250 Directory successfully changed"
11/29/2013 11:37:22 (aikuma 192.168.1.1-->192.168.1.2:21) "MKD a341c959-fa80-45cc-83dc-e6b075559ed3"
11/29/2013 11:37:22 (aikuma 192.168.1.1<--192.168.1.2:21) "257 "/a341c959-fa80-45cc-83dc-e6b075559ed3/" directory created."
11/29/2013 11:37:22 (aikuma 192.168.1.1-->192.168.1.2:21) "RMD a341c959-fa80-45cc-83dc-e6b075559ed3"
11/29/2013 11:37:22 (aikuma 192.168.1.1<--192.168.1.2:21) "250 Directory removed"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "PWD"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "257 "/""
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "CWD /"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "250 Directory successfully changed"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "MKD 08b6cf2b-de3c-4bba-a67a-f8bdcba5a039"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "257 "/08b6cf2b-de3c-4bba-a67a-f8bdcba5a039/" directory created."
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "RMD 08b6cf2b-de3c-4bba-a67a-f8bdcba5a039"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "250 Directory removed"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "PWD"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "257 "/""
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "CWD /"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "250 Directory successfully changed"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "MKD //."
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "504 Invalid command parameter"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "CWD //."
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "250 Directory successfully changed"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "PORT 192,168,1,1,220,128"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "200 PORT command successful"
11/29/2013 11:37:23 (aikuma 192.168.1.1-->192.168.1.2:21) "NLST"
11/29/2013 11:37:23 (aikuma 192.168.1.1<--192.168.1.2:21) "550 Can't find file"

FileZilla FTP server works without issues:

(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> Connected, sending welcome message...
(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> 220-FileZilla Server version 0.9.41 beta
(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> 220-written by Tim Kosse (Tim.Kosse@gmx.de)
(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> 220 Please visit http://sourceforge.net/projects/filezilla/
(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> USER aikuma
(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> 331 Password required for aikuma
(000001)29/11/2013 11:49:04 - (not logged in) (192.168.1.1)> PASS 
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 230 Logged on
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> TYPE I
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 200 Type set to I
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> CWD /
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 250 CWD successful. "/" is current directory.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> MKD 1560bff7-6f3d-402b-9348-51d56a3184f9
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 257 "/1560bff7-6f3d-402b-9348-51d56a3184f9" created successfully
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> RMD 1560bff7-6f3d-402b-9348-51d56a3184f9
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 250 Directory deleted successfully
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> PWD
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 257 "/" is current directory.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> CWD /
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 250 CWD successful. "/" is current directory.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> MKD f9f7c019-ab0b-4875-8826-694f7fa81178
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 257 "/f9f7c019-ab0b-4875-8826-694f7fa81178" created successfully
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> RMD f9f7c019-ab0b-4875-8826-694f7fa81178
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 250 Directory deleted successfully
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> PWD
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 257 "/" is current directory.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> CWD /
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 250 CWD successful. "/" is current directory.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> MKD //.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 550 Directoryname not valid
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> CWD //.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 250 CWD successful. "/" is current directory.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> PORT 192,168,1,1,179,134
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 200 Port command successful
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> NLST
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 150 Opening data channel for directory list.
(000001)29/11/2013 11:49:04 - aikuma (192.168.1.1)> 226 Transfer OK
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> MKD recordings
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 257 "/recordings" created successfully
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> MKD //./recordings
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 550 Directory already exists
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> CWD //./recordings
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 250 CWD successful. "/recordings" is current directory.
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> PORT 192,168,1,1,204,94
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 200 Port command successful
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> NLST
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 150 Opening data channel for directory list.
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 226 Transfer OK
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> PORT 192,168,1,1,168,245
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 200 Port command successful
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> STOR //./recordings/2fa03b2a-c8f1-486d-9a4b-c8c20d41feb8.wav.inprogress
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 150 Opening data channel for file transfer.
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 226 Transfer OK
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> RNFR //./recordings/2fa03b2a-c8f1-486d-9a4b-c8c20d41feb8.wav.inprogress
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 350 File exists, ready for destination name.
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> RNTO //./recordings/2fa03b2a-c8f1-486d-9a4b-c8c20d41feb8.wav
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 250 file renamed successfully
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> PORT 192,168,1,1,197,239
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> 200 Port command successful
(000001)29/11/2013 11:49:05 - aikuma (192.168.1.1)> STOR //./recordings/22b02a61-efae-4eea-8cc2-ca73c27cc36c.wav.inprogress

My intuition is that the Xlite and smallftpd supply of a 550 when calling ls on an empty directory is the cause. This is legal behavior. At any rate, Filezilla is attested as a working FTP server solution for Windows that may be set up in a matter of seconds.

**Comment by stevenbird** [comment]
Superseded by #386
