### ISSUE TITLE
Add new user name field disappears on small handsets

### ISSUE THREAD

**Issue by LaurenGawne** [langtech/aikuma#133]
On adding user screen the dialog box for adding a new user name disappears off the top of the screen when you click on it and it opens the keyboard. Only the language adding and the cancel/accept buttons remain. You can still type but you can't see what's being typed. 

Could we rearrange the buttons or turn this into a scrolling screen?

**Comment by stevenbird** [comment]
This is no longer a problem, now that the activity has been split into several smaller activities.
