### ISSUE TITLE
Is adding a title important? Do we need to make it more obvious

### ISSUE THREAD

**Issue by LaurenGawne** [langtech/aikuma#146]
I've inadvertently skipped adding a title at least 4 times now. It isn't obvious enough and the process lets you save without one. Clearly it's not important to the process you're trying to get going, but is there a way that people can add it later? They might be upset they can't add a title.

**Comment by stevenbird** [comment]
We've now created a separate activity for adding the title, so it's impossible to miss this step. The respeakings and translations do not have their own title any more.
