### ISSUE TITLE
Web API for "index" interface

### ISSUE THREAD

**Issue by hleeldc** [langtech/aikuma#316]
(LP-40 moved to this issue.)

Re-implement org.lp20.aikuma.storage.Index as a web interface running on the Index Server.

We should be able to tell whether the index request is coming from aikuma app. We want to reject the calls if they originate from elsewhere. The following link may provide some information on how to do it.

http://android-developers.blogspot.com/2013/01/verifying-back-end-calls-from-android.html

**Comment by hleeldc** [comment]
The PR #375, originally #354, has been merged. Working on deployment.

**Comment by hleeldc** [comment]
@parker-ldc -- The server has been deployed, but I'm having trouble with SSL stuff. Both `require_auth` and `use_ssl` are set to `yes`. I can connect to the server, e.g. the `openssl s_client -connect` command seems to work find. But when I open a stream from an HttpURLConnection object and write some post data, it gives me this error.

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Any idea?

**Comment by hleeldc** [comment]
@parker-ldc -- One more question. See [this line](https://github.com/langtech/aikuma/blob/master/AikumaCloudServer/index_server/src/main/java/org/lp20/aikuma/servers/index_server/Main.java#L54) for context.

Between the index server and the client, there is no sensitive information passed around. It's just metadata of files. The client authentication is between the server and the google server, which is taken care of by the google library. So, I'm wondering why we recommend SSL between our server and the clients.

**Comment by parker-ldc** [comment]
Uh. I'll have to look into it, but if I had to guess, it's complaining about a self signed certificate.

**Comment by parker-ldc** [comment]
The SSL is for protecting the auth tokens, rather than the data. Anyone that can see the traffic can just take a token and do index operations with it. 

If that's not something you care about, or don't think will be a big deal, then feel free to disable SSL.

**Comment by hleeldc** [comment]
I see. I now see that auth token is passes in the http header. Probably, it's necessary for us to get our server key certified.

**Comment by stevenbird** [comment]
Once #384 is merged, this can be closed.

**Comment by stevenbird** [comment]
@hleeldc please put the API documentation in the [Aikuma Wiki](https://github.com/aikuma/aikuma/wiki)

**Comment by hleeldc** [comment]
Created a wiki page here: https://github.com/aikuma/aikuma/wiki/Cloud-Server-API.

It includes the new file sharing method too.

**Comment by stevenbird** [comment]
Thanks @hleeldc
