### ISSUE TITLE
Storing speaker related files on central google drive

### ISSUE THREAD

**Issue by hleeldc** [langtech/aikuma#320]
Store speaker related files including speaker image and json files so that users can download and review recordings collected by other users.

**Comment by stevenbird** [comment]
@lisaslyis please test this.

**Comment by lisaslyis** [comment]
Test is done:
`SpekaerID-small-image.jpg` and `SpakerID-metadata.json` files are now moved to Central GoogleDrive and logged in FusionTable like all the other files, when it's stored in private GoogleDrive.
