### ISSUE TITLE
Item download in cloud-search interface

### ISSUE THREAD

**Issue by lisaslyis** [langtech/aikuma#368]
Quick-action button for item download will download all files related to the item.
1. Original recording file, metadata and transcript files
2. Derivative recording files(commentaries, translation, ...), metadata and mapping files
3. Speaker images and metadata

The interface will follow #364

**Comment by stevenbird** [comment]
This is blocked on #370.

**Comment by stevenbird** [comment]
Give user a toast `n items queued for download`

**Comment by stevenbird** [comment]
Resolved by #417
