### ISSUE TITLE
New file sharing approach for google drive

### ISSUE THREAD

**Issue by hleeldc** [langtech/aikuma#370]
Instead of copying file from private google drive to central google drive by http downloading, use google api function to update permission on the file to share with the google account managing the central google drive.

This will make issue #347 irrelevant.

**Comment by hleeldc** [comment]
We might want to implement something similar, reversed direction from central google drive to private google drive, for #364.

**Comment by hleeldc** [comment]
Part of this is implemented by #390.

**Comment by stevenbird** [comment]
The central to private sharing still needs to be completed.

**Comment by stevenbird** [comment]
@hleeldc please lease assign this to @lisaslyis once you have finished your work so he can update the code on the client side.

**Comment by hleeldc** [comment]
@lisaslyis -- I'm still working on this, but you can start writing client code against the following interface. The server will accept the following "share" request.

PUT /file/{identifier}/share/{email}
X-Aikuma-Auth-Token: {id-token}

No request body. It returns 200 on success, and 404 on failure.

The full URL for the request can be computed like this:


```java
URL baseurl = new java.net.URL(AikumaSettings.getIndexServerUrl());
URL requestUrl = new java.net.URL(baseurl, "/file/.../share/...");
```

**Comment by stevenbird** [comment]
This is resolved by https://github.com/langtech/aikuma/pull/405
