### ISSUE TITLE
Extend FusionIndex2 to support query for item updates

### ISSUE THREAD

**Issue by stevenbird** [langtech/aikuma#380]
Issue #371 requires the ability to query a list of item_ids for any updates. (Such an update would occur when a 3rd party creates a commentary for an item that is already downloaded to the phone.) The FusionIndex2 interface needs to support queries that provide a (long) list of item_ids.

**Comment by hleeldc** [comment]
Just to summarize FusionTables limits:
- 25k queries per day
- 30 queries per minute
- Read counts as 1 query, write counts as 5

**Comment by stevenbird** [comment]
Include support for a `user_id` parameter, so that we only find out about updates to items that are owned by this user. This is to support sync between multiple devices owned by the same person.

**Comment by hleeldc** [comment]
Just realized that the table already has the `user_id` field. This means that files can be searched by user id.
