### ISSUE TITLE
Accessing Google Drive with non-Aikuma files

### ISSUE THREAD

**Issue by stevenbird** [langtech/aikuma#381]
When a Google Drive contains a large number of files, Aikuma is too slow in finding the Aikuma files, because it is doing a linear search. Is there a more efficient way to search for files by regular expression pattern?

**Comment by stevenbird** [comment]
We can use the idea of file properties (#360) to only select files created by Aikuma, then check that the root file has the appropriate id.

**Comment by hleeldc** [comment]
What are the context of this issue? I'm trying to see if such capability is really needed.

**Comment by lisaslyis** [comment]
@hleeldc Aikuma sync operation is done with GoogleDriveStorage without the help of FusionIndex. So there should be a mechanism to extract only aikuma-related files in GoogleDrive, otherwise, it needs to   check all files in GoogleDrive

**Comment by hleeldc** [comment]
With PR #390, `GoogleDriveStorage#list` now lists only the files inside the aikuma root folder. Google drive can return 1000 entries per request. Most of the projects will fit in a couple of REST API calls. Scanning a directory of this size shouldn't be too bad. A list of all files in the local phone can be efficiently maintained if needed. Computing difference of two sets of this size should be quick enough. Isn't this enough? Actually, it doesn't sound good for an android app to manage more than a few thousand files in its local storage.

**Comment by stevenbird** [comment]
This should be resolved by https://github.com/langtech/aikuma/pull/390

**Comment by stevenbird** [comment]
Resolved by #396
