### ISSUE TITLE
Open file / import 3gpp file ?

### ISSUE THREAD

**Issue by Netesten** [langtech/aikuma#571]
I made a voice recording on my Asus Zenfone 5 and when I looked to open in Aikuma, it pronounced the 3gpp file as not an audio file. Do I need to use a converter and if so, which do you recommend?  and what am I converting to (.mp3)?

**Comment by Netesten** [comment]
I downloaded a free mp3 recorder from PlayStore and was able to open that and save in Aikuma. Might want a mention of supported file types in your user notes ?

**Comment by Lingomat** [comment]
More good points, if in the wrong place :) Yeah so 3gpp just isn't ever going to work. You just install a proper voice record app. Actually, our import really should do a good job of telling people what you can import and also try to work out if something isn't supported. Apparently it just silently swallows it for now.  I'll make an issue about this.
