### ISSUE TITLE
Annotate help popup window position & adding an annotation to a small piece of recording

### ISSUE THREAD

**Issue by Netesten** [langtech/aikuma#573]
Would it be possible to get the popup help to open up lower down on the screen, so I can look at what it's referring to?

**Comment by Netesten** [comment]
I want to select a piece of recording where one word is used and another translated and add an annotation to that part but I cannot work it out. Will try again.

**Comment by Netesten** [comment]
OK, just wondering: sometimes on YouTube, people use the timer to indicate when a moment starts. Can the waveform get a time, so in the annotation I can say: from 0:50 - 0.55 speakers refers to X but means Y ? There is a ruler thing, but the measurements need be more precise?

**Comment by Lingomat** [comment]
1. We could but it wouldn't help. You can't click outside of the help dialog and work while the pop up stays visible.
2. The measurements are precise to the millisecond. Are you trying to click on the waveform to do this? Why not use the play controls to mark these regions?
