### ISSUE TITLE
"Visual Commentaries"

### ISSUE THREAD

**Issue by floere** [langtech/aikuma#64]
We'd like to allow an Aikuma user to attach pictures to a recording.

UI:
- Thumbnail shown under the commentaries, looking like the commentaries (e.g. http://lp20.org/aikuma/design.html#playing_page), but with a thumbnail of the photo instead of the speaker.

Files:
- In the recording's directory, under /pictures, using a unique id.

Synchronised?
- Yes. Like everything else.

**Comment by stevenbird** [comment]
This has not been raised as a priority by current users; closing.
