### ISSUE TITLE
Filter/sort recordings when selecting them

### ISSUE THREAD

**Issue by floere** [langtech/aikuma#7]
Context:
- A day's recoding with multiple devices may yield well over 50-100 recordings.
- This results in many recordings being available for respeaking/interpreting/listening.

User's goals:
- I want to listen to a specific person's recordings. How does that person find all the recordings by one person? How do they identify that person?
- I want to listen to today's recordings/a specific date's recordings.

Group/Sort:
- by User
- by Date

Filter:
- by User (Select picture from grid, picture+name from list? – also add "nil" user for not filtering)
- by Date (Select "today", "yesterday", ... dates from calendar view? - also add "no filter" for not filtering)

Can both filters and grouping/sorting be used together? (Florian thinks so)

**Comment by stevenbird** [comment]
The date sorting requirement is already met by the item listing screen. The speaker sorting requirement is superseded by #409.
